/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package po_7_2;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import java.util.Iterator;
import java.util.Random;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.LinkedBlockingQueue;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class frame1 extends javax.swing.JFrame {
    
    Random rand;    
    JLabel ball;
    private final int N  = 4;
    Point pressedPoint;
    BlockingQueue array;
    MouseClick mouseClick ;
    Listener listener;
    Point hunterPoint;
    Hunter hunter;
    public void setHunterPoint(Point p){
        hunterPoint = p;
    }
    
    
    
    private void createLables(){
       
        for (int i = 0; i < N; i++){
            Duck d = new Duck(i,this);
            array.add(d);
            d.start();
            
        }
    }
    
    public void setPoint(Point p){
            Iterator iter = array.iterator();
            while (iter.hasNext()){
                Duck duck = (Duck) iter.next();
                duck.setPoint(p);
            }
    }

    public frame1() {
        initComponents();
        mouseClick = new MouseClick(this);
        listener = new Listener(this);
        rand = new Random();
        pressedPoint = new Point();
        this.getContentPane().setBackground(new Color(153,204,255));
        this.setSize(800, 700);
        this.repaint();
        array = new LinkedBlockingQueue();
        this.addMouseListener((MouseListener) mouseClick);
        this.addKeyListener((KeyListener)listener);
        this.setResizable(false);
        createLables();
        createBall();
        hunterPoint = new Point(0,this.getHeight() - 100);
        hunter = new Hunter(hunterPoint,this);
        hunter.start();
    }
    private void createBall(){
           ball = new JLabel();
            ImageIcon imageIcon = new ImageIcon(this.getClass().getResource("ball.gif"));
            int h = imageIcon.getIconHeight();
            int w = imageIcon.getIconWidth();
            ball.setBounds(this.getHeight() - h,this.getWidth()-2*h,w,h);
            ball.setIcon(imageIcon);
            ball.setVisible(true);
            this.add(ball);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        ball.setLocation(evt.getXOnScreen(),this.getHeight() - 2*ball.getHeight());
    }//GEN-LAST:event_formMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
