/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package po_7_1_1;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.Random;
import java.util.concurrent.Semaphore;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.logging.Level;
import java.util.logging.Logger;

public class NewJFrame extends javax.swing.JFrame {
    private int  [][] array ;
    private final int width,height;
    private final int div;
    private final Graphics grap;
    private final WorkQueue wq;
    private final int numThreads = 5;
    private int [][] arrayAdd;
    private final int divArray;
     private AtomicInteger hasFinished;

    public NewJFrame() {
        initComponents();
        setVisible(true);
        this.setBackground(Color.DARK_GRAY);
        this.setSize(860,660);
        jPanel1.setSize(800,600);
        grap = jPanel1.getGraphics();
        this.setResizable(false);
        width = jPanel1.getWidth();
        height = jPanel1.getHeight() ;
        div = 5;

        wq = new WorkQueue(numThreads);
        divArray = width / numThreads;
        array = new int[width/div][height/div];
        arrayAdd = new int[width/div][height/div];
        jPanel1.setBackground(Color.DARK_GRAY);
        initColony();
        updateColony();
        repaint();

    }
    private void initColony(){
        Random rand = new Random();
        for (int i = 0; i< width/div;i++)
            for (int j = 0; j< height/div;j++){
                int v = rand.nextInt(20);
                if (v % 5 == 0 ) v = 0;
                if (v % 2 == 0 ) v = 0;
                if (v % 3 == 0 ) v = 0;
                if (v % 7 == 0 ) v = 0;
                if (v % 11 == 0 ) v = 0;
                if (v % 13 == 0 ) v = 0;
              if (v % 17 == 0 ) v = 0;
               // if (v % 19 == 0 ) v = 0;

                if (v != 0) v = 1;
                array[i][j] = v;
            }
    }

    class updateLine implements Runnable{
        private int numb;
        public updateLine(int numThread){
            numb = numThread;
        }
        @Override
         public void run(){
            System.out.println("start " + numb);
            for (int i = numb*divArray; i< width/div && i < divArray*( numb + 1);i++)
            for (int j = 0; j< height/div;j++){
                int sum = 0;
                if (i > 0){
                    if (j > 0) { if (array[i-1][j-1] > 0) sum++;}
                    if (array[i-1][j] > 0) sum++;
                    if (j < height/div - 1) { if (array[i-1][j+1] > 0) sum++;}
                }
                if (i < width/div - 1 ){
                   if (j > 0) { if (array[i+1][j-1] > 0) sum++;}
                    if (array[i+1][j] > 0) sum++;
                    if (j < height/div - 1) { if (array[i+1][j+1] > 0) sum++;} 
                }
                 if (j > 0) { if (array[i][j-1] > 0) sum++;}
                  if (j < height/div - 1) { if (array[i][j+1] > 0) sum++;}                                 
                arrayAdd[i][j] = 0;
                   if (sum == 3 )arrayAdd[i][j] = 1;
                if (sum == 2 &&  array[i][j] == 1)arrayAdd[i][j] = 1;
            }
                           System.out.println("stop " + numb);
                           hasFinished.incrementAndGet();

         }
    }
    
    
    private void updateColony(){
        hasFinished = new AtomicInteger(0);
        for (int i = 0; i < numThreads; i++)
            wq.execute(new updateLine(i));
        while (hasFinished.get()!= numThreads){}
        System.out.println("stop doing ");         
    }
    private void drawColony(){
           grap.setColor(Color.BLUE);
            for (int i = 0; i < width/div;i++)
                for (int j = 0; j< height/div;j++){
                    if (arrayAdd[i][j] == 1){
                        grap.fillRect(i*div, j*div,div, div);
                    }
                     array[i][j] = arrayAdd[i][j];
                }          
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        // jPanel1.setBackground(Color.red);
         System.out.println("jkbk");
       
       // add(rects);
        //rects.setVisible(true);
        
    }//GEN-LAST:event_formMouseClicked
    @Override
    public void repaint(){
        
        super.repaint();
        while(true){
            drawColony();
                        updateColony();
            try {
                Thread.sleep(200);
            } catch (InterruptedException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
          grap.clearRect(0, 0, width, height);
        }
    }
    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        Point p = this.getMousePosition();
       
        System.out.println(p.getX()+" "+ p.getY());
        grap.setColor(Color.red);
          grap.drawOval(p.x, p.y,10,10);
       //  initField();
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
